source :rubygems
gem 'thin'
gem 'rspec'
gem 'thor'
gem 'bunny'
gem 'activesupport'
gem 'activerecord'
gem 'pg'
gem 'sinatra'
gem 'haml'
gem 'sinatra-contrib'
gem 'slim'
gem 'rack-flash3'
gem 'warden'
gem 'warden-hmac-authentication', :git => "git://github.com/gregory-m/warden-hmac-authentication.git"
gem 'faraday'
